version: '2'

services:
  shadowsocks_server:
    image: sebreiro/shadowsocks-go-docker:1.2.1
    container_name: shadowsocks_server
    restart: unless-stopped
    command: shadowsocks-server -u
    volumes:
      - /etc/shadowsocks:/etc/shadowsocks
    ports:
      - 8387:8387
      - 8387:8387/udp
      - 8388:8388
      - 8388:8388/udp
    networks:
      - ss_server
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  shadowsocks_client:
    image: sebreiro/shadowsocks-go-docker:1.2.1
    container_name: shadowsocks_client
    restart: unless-stopped
    command: shadowsocks-local
    volumes:
      - /etc/shadowsocks:/etc/shadowsocks
    ports:
      - 8387:8387
      - 8388:8388
    networks:
      - ss_client
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
      
networks:
  ss_server:
    driver: bridge
    name: ss_server
  ss_client:
    driver: bridge
    name: ss_client